### ISSUE TITLE
`Create.html` template course video [indentation error]

### ISSUE THREAD

**Issue by RanaivosonHerimanitra** [CodeUpStart/project-kickstarter-starter#1]
Hi there,
I've followed step by step this video part of the course but always got an indentation error. Could you guide me to solve this error? 
Here is a portion of my code from the `/projects/create` route.

```
@app.route("/projects/create",methods=['GET','POST'])
def create():
    if request.method=="GET":
        return render_template("create.html")

    if request.method=="POST":
        now = datetime.datetime.now()
        time_end= request.form.get("funding_end_date")
        time_end= datetime.datetime.strptime(time_end,"%Y-%m-%d")
        new_project = Project(
            member_id = 1,
            name = request.form.get("project_name"),
            short_description = request.form.get("short_description"),
            long_description = request.form.get("long_description"),
            goal_amount = request.form.get("funding_goal"),
            time_start = now,
            time_end = time_end,
            time_created = now
            )
        db.session.add(new_project)
        db.session.commit()
        return redirect(url_for('create'))
```

**Comment by chezmix** [comment]
Which line is the indentation error on?

**Comment by RanaivosonHerimanitra** [comment]
When I declare `new_project`

**Comment by RanaivosonHerimanitra** [comment]
I have a reproducible example [here](https://github.com/RanaivosonHerimanitra/punchstarter_demo_error)

**Comment by chezmix** [comment]
If you look at the raw file, you can see that the indentation isn't correct on the line before the new_project declaration:

https://raw.githubusercontent.com/RanaivosonHerimanitra/punchstarter_demo_error/master/punchstarter/__init__.py

If you're using sublime, you can easily see the whitespaces with a setting.  http://stackoverflow.com/questions/10153998/sublime-text-2-view-whitespace-characters

**Comment by RanaivosonHerimanitra** [comment]
thanks so much, stupid error!
