### ISSUE TITLE
Datetime error when a new project is submitted

### ISSUE THREAD

**Issue by RanaivosonHerimanitra** [CodeUpStart/project-kickstarter-starter#2]
Hi,

I'd like to figure out what's wrong with my code again. After I submit the form for a new project, It reports that my time data doesn't match format or I followed exactly what you did in the video.

Something I found weird also: I didn't get the date picker as yours even if I set the `input type` to `date`
Has It something to do with this error?

Here are some [snapshots](https://github.com/RanaivosonHerimanitra/punchstarter_demo_error)

**Comment by chezmix** [comment]
Yes, it seems that your version of firefox doesn't have the datepicker like my chrome browser does.

It's expecting dashes between the numbers instead of slashes. Try putting 10-10-2015 instead of 10/10/2015.

**Comment by RanaivosonHerimanitra** [comment]
I tried it on chrome using datepicker . It gave me:

`TypeError: 'time_end' is an invalid keyword argument for Project`

**Comment by RanaivosonHerimanitra** [comment]
Ok , I figured it out:
`time_end` is not a variable in my  `Project` table.  Instead , It was `time_ended`
